server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: personal-blogging-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blogdb}
    username: ${SPRING_DATASOURCE_USERNAME:zh}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: mappings
